# Generated by Django 4.2.2 on 2023-07-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_address_line_1_userbase_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='state',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
